name: Deploy Preparation

on:
  push:
    branches:
      - main

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Validate server configuration
      run: |
        python -c "import unified_server; print('Server configuration valid')"
        
    - name: Check Railway configuration
      run: |
        if [ -f "railway.json" ]; then
          echo "Railway configuration found"
        else
          echo "Warning: railway.json not found"
        fi
        
    - name: Prepare for deployment
      run: |
        echo "MCP-AutoPRX is ready for Railway deployment"
        echo "All configurations validated successfully"